language: php
php:
  - 7.3
  - 7.4
  - nightly

matrix:
  allow_failures:
    - php: nightly

env:
  - USE_OPCACHE=1 USE_ZEND_ALLOC=0
  - USE_OPCACHE=1 USE_ZEND_ALLOC=1
  - USE_OPCACHE=0 USE_ZEND_ALLOC=0
  - USE_OPCACHE=0 USE_ZEND_ALLOC=1

before_script:
  - |
    if [[ "$USE_OPCACHE" == "1" ]]; then
      echo "zend_extension=opcache.so" >> ./php.ini
      echo "opcache.enable=1" >> ./php.ini
      echo "opcache.enable_cli=1" >> ./php.ini
    fi

script:
  - phpize
  - ./configure
  - make
  - make install
  - echo "extension=pthreads.so" >> ./php.ini
  - php ./run-tests.php -P -q --show-diff -n -c ./php.ini

#notifications:
#  webhooks:
#    urls:
#      - https://webhooks.gitter.im/e/428fac7bd9f4b867c347
#    on_success: always
#    on_failure: always
#    on_start: always
